---

# Workstation name
workstation: "7100"

# Ip Address of scoreboard
ipAddress: "10.19.15.24"

# Triggers polling on application startup
# Should always be True unless debugging
pollOnStart: True

# Software version
version: 1.0

### Browser Path
# Chrome
browserPath: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
# IE
# browserPath: "C:/Program Files/Internet Explorer/iexplore.exe"